// GitHub Pages + Firebase Realtime Database version.
// 1) Create a Firebase project.
// 2) Enable Authentication -> Anonymous.
// 3) Create Realtime Database.
// 4) Paste your Firebase web config below.
// 5) Add the rules from README.md.
// IMPORTANT: Never put a real admin password in client-side JS.

import {initializeApp} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import {getDatabase,ref,set,get,onValue,push,update,remove} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import {getAuth,signInAnonymously,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";

const firebaseConfig={apiKey:"PASTE_API_KEY",authDomain:"PASTE_PROJECT.firebaseapp.com",databaseURL:"https://PASTE_PROJECT-default-rtdb.firebaseio.com",projectId:"PASTE_PROJECT",storageBucket:"PASTE_PROJECT.firebasestorage.app",messagingSenderId:"PASTE_SENDER_ID",appId:"PASTE_APP_ID"};
const app=initializeApp(firebaseConfig),db=getDatabase(app),auth=getAuth(app);
let uid="",room="",roomType="public",me="",players=[],selected=null,rot=0,spinning=false,round=1;
const A=["😎","😈","🤠","🦊","🐼","🐯","🐸","👽","🤖","🥳"];
const T=["What is your funniest harmless secret?","What is your most useless talent?","Who here would survive longest in the wild?","What is your funniest school memory?","What is the funniest excuse you have ever used?","What harmless thing are you surprisingly competitive about?","What is your weirdest food combination?"];
const D=["Do your funniest dance for 20 seconds.","Speak like a robot for one round.","Give everyone a dramatic compliment.","Act like a news reporter describing this room.","Make your funniest face for 10 seconds.","Sing a song using only 'la la la'.","Do your best movie-trailer voice for 20 seconds."];
const $=x=>document.getElementById(x); const screens=["home","public","lobby","game","admin"];
function show(x){screens.forEach(s=>$(s).classList.remove("active"));$(x).classList.add("active");scrollTo(0,0)}
function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>$("toast").classList.remove("show"),2200)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function gen(){return [...Array(6)].map(()=> "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*31)]).join("")}
function roomPath(){return ref(db,"rooms/"+room)}
async function create(){room=gen();while((await get(ref(db,"rooms/"+room))).exists())room=gen();players=[{uid,name:"Host",avatar:A[0],host:true}];me="Host";await set(roomPath(),{type:roomType,status:"active",createdAt:Date.now(),started:false,players:{[uid]:players[0]}});openLobby();toast("Room created 🎉")}
async function joinRoom(c){c=(c||$("joinCode").value).trim().toUpperCase();if(!c)return toast("Enter a room code.");const s=await get(ref(db,"rooms/"+c));if(!s.exists())return toast("Room not found.");const r=s.val();const ps=Object.values(r.players||{});if(r.status==="closed")return toast("Room is closed.");if(ps.length>=10&&!r.players[uid])return toast("Room is full.");room=c;roomType=r.type;me=$("playerName").value.trim()||"Player";if(!r.players?.[uid])await update(ref(db,"rooms/"+room+"/players/"+uid),{uid,name:me,avatar:A[ps.length%10],host:false});openLobby()}
function openLobby(){show("lobby");$("code").textContent=room;$("privacy").textContent=roomType==="public"?"PUBLIC":"PRIVATE";listenRoom()}
function listenRoom(){onValue(roomPath(),s=>{if(!s.exists()){toast("Room no longer exists.");show("home");return}const r=s.val();roomType=r.type;players=Object.values(r.players||{});$("count").textContent=players.length+"/10";$("players").innerHTML=players.map(p=>`<div class="player"><span>${p.avatar}</span><b>${esc(p.name)}${p.host?" 👑":""}</b></div>`).join("");$("mini").innerHTML=players.map(p=>`<span>${p.avatar} ${esc(p.name)}</span>`).join("");if(r.started&&$("game").classList.contains("screen")&&!$("game").classList.contains("active"))openGame()})}
async function addPlayer(){const n=$("playerName").value.trim();if(!n)return toast("Enter a display name.");const s=await get(ref(db,"rooms/"+room+"/players"));if(Object.keys(s.val()||{}).length>=10)return toast("Maximum 10 players.");me=n;await update(ref(db,"rooms/"+room+"/players/"+uid),{uid,name:n,avatar:A[Object.keys(s.val()||{}).length%10],host:false});toast("You're in!")}
async function start(){if(players.length<2)return toast("Need at least 2 players.");await update(roomPath(),{started:true});openGame()}
function openGame(){show("game");$("gameCode").textContent=room;listenChat();listenGame()}
function listenGame(){onValue(ref(db,"rooms/"+room+"/game"),s=>{const g=s.val();if(!g)return;if(g.round)round=g.round;$("round").textContent=round;if(g.selected){selected=g.selected;$("selAvatar").textContent=selected.avatar;$("selName").textContent=selected.name;$("selected").classList.remove("hidden");$("choices").classList.remove("hidden")}})}
async function spin(){if(spinning||players.length<2)return;spinning=true;$("spin").disabled=true;const p=players[Math.floor(Math.random()*players.length)];rot+=360*7+Math.floor(Math.random()*360);$("bottle").style.transform=`rotate(${rot}deg)`;setTimeout(async()=>{await set(ref(db,"rooms/"+room+"/game"),{round,selected:p,updatedAt:Date.now()});spinning=false;$("spin").disabled=false;toast(p.name+" was chosen! 😈")},4100)}
async function choose(kind){const arr=kind==="TRUTH"?T:D,q=arr[Math.floor(Math.random()*arr.length)];await update(ref(db,"rooms/"+room+"/game"),{kind,prompt:q});$("promptType").textContent=kind;$("promptIcon").textContent=kind==="TRUTH"?"❤️":"🔥";$("promptText").textContent=q;$("choices").classList.add("hidden");$("prompt").classList.remove("hidden")}
function next(){round++;$("round").textContent=round;$("selected").classList.add("hidden");$("choices").classList.add("hidden");$("prompt").classList.add("hidden");$("instruction").textContent="Spin the bottle and let fate decide."}
async function send(text){text=text.trim();if(!text)return;await push(ref(db,"rooms/"+room+"/chat"),{name:me,text,uid,time:Date.now()});$("chatInput").value=""}
function listenChat(){onValue(ref(db,"rooms/"+room+"/chat"),s=>{const v=s.val()||{};$("messages").innerHTML=Object.values(v).slice(-100).map(m=>`<div class="msg ${m.uid===uid?"mine":""}"><b>${esc(m.name)}</b>${esc(m.text)}</div>`).join("");$("messages").scrollTop=$("messages").scrollHeight})}
async function browse(){const s=await get(ref(db,"rooms"));const rs=Object.values(s.val()||{}).filter(r=>r.type==="public"&&r.status==="active"&&Object.keys(r.players||{}).length<10);$("publicCount").textContent=rs.length;$("rooms").innerHTML=rs.length?rs.map(r=>`<div class="panel" style="margin:10px 0;display:flex;justify-content:space-between;align-items:center"><div><b>Public Party</b><div class="muted">${r.type} · ${Object.keys(r.players||{}).length}/10</div></div><button class="smallBtn" data-code="${r.code||""}">Join</button></div>`).join(""):`<div class="panel muted">No open public rooms right now.</div>`;show("public");$("rooms").querySelectorAll("[data-code]").forEach(b=>b.onclick=()=>joinRoom(b.dataset.code))}
async function leave(){if(room)await update(roomPath(),{status:"closed",closedAt:Date.now()});room="";show("home")}
async function adminData(){const s=await get(ref(db,"rooms"));const rs=Object.entries(s.val()||{});const active=rs.filter(([,r])=>r.status!=="closed"),closed=rs.filter(([,r])=>r.status==="closed");$("total").textContent=rs.length;$("active").textContent=active.length;$("closed").textContent=closed.length;$("playersTotal").textContent=rs.reduce((n,[,r])=>n+Object.keys(r.players||{}).length,0);$("roomTable").innerHTML=rs.map(([c,r])=>`<div class="row"><b>${c}</b><span>${r.type}</span><span class="status ${r.status==="closed"?"closed":"active"}">${r.status}</span><button class="smallBtn" data-open="${c}">Open</button></div>`).join("");$("roomTable").querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>{room=b.dataset.open;openLobby()})}
function adminLogin(){const u=$("adminUser").value,p=$("adminPass").value;if(u==="siralajii"&&p==="Bharat@2007"){sessionStorage.admin="1";$("modal").classList.add("hidden");show("admin");adminData()}else toast("Invalid admin credentials.")}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");roomType=b.dataset.type;$("modeText").textContent=roomType==="public"?"Anyone can discover this room.":"Only people with the room code can join."});
$("create").onclick=create;$("join").onclick=()=>joinRoom();$("browse").onclick=browse;$("add").onclick=addPlayer;$("start").onclick=start;$("spin").onclick=spin;$("truth").onclick=()=>choose("TRUTH");$("dare").onclick=()=>choose("DARE");$("next").onclick=next;$("send").onclick=()=>send($("chatInput").value);$("copy").onclick=()=>navigator.clipboard?.writeText(room).then(()=>toast("Code copied!"));$("leave").onclick=leave;$("lobbyHome").onclick=leave;$("adminBtn").onclick=()=>$("modal").classList.remove("hidden");$("x").onclick=()=>$("modal").classList.add("hidden");$("login").onclick=adminLogin;$("adminHome").onclick=()=>show("home");$("logout").onclick=()=>{sessionStorage.removeItem("admin");show("home")};$("deleteClosed").onclick=async()=>{const s=await get(ref(db,"rooms"));for(const [c,r] of Object.entries(s.val()||{}))if(r.status==="closed")await remove(ref(db,"rooms/"+c));adminData();toast("Closed rooms deleted.")};$("chatInput").addEventListener("keydown",e=>{if(e.key==="Enter")send(e.target.value)});document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>send((b.dataset.q==="truth"?"TRUTH: ":"DARE: ")+["Ask me something funny!","Do your funniest challenge!","Tell us a party joke!"][Math.floor(Math.random()*3)]));document.querySelectorAll("[data-home]").forEach(b=>b.onclick=()=>show("home"));
onAuthStateChanged(auth,u=>{if(u)uid=u.uid});signInAnonymously(auth).catch(()=>toast("Firebase setup is required."));
